### ISSUE TITLE
The stakeholder counts/distribution are not shown in the map

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#100]
* A stakeholder can define its country in the sign-up form. When using the *toggle* in the map, we should show the same counts/magnitude as the other *resources*. Right now shows an empty map.![2021-02-17_1565x660.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/74579daf-624d-4526-937b-87e244fda841)

**Comment by dedenbangkit** [comment]
Updated query

![Screen Shot 2021-02-17 at 15.26.38.png](https://images.zenhubusercontent.com/600c532b852e9f29c0227e40/06fcad0d-97f4-44d4-9ee7-2884068b5eab)

**Comment by iperdomo** [comment]
The country stakeholder count must be based on the profile country, not the user geo_coverage
