### ISSUE TITLE
Do we need to keep the 'Submission Approved' in profile page?

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#101]
We're showing a label *"Submission is approved"* every time the user visits the profile. Do we need to show it always? Only for rejected? Only one time (e.g. via cookie) ?

![2021-02-17_579x200.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/8f5ac526-1849-4960-9618-a1aa2149ccbb)

**Comment by dedenbangkit** [comment]
Done via `document.cookie`.

- Rejected, Submitted: Always Show
- Approved: only one time
