### ISSUE TITLE
Hide dates from footer latest topics + enable link

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#105]
- [ ] In the footer we have a *date* of creation of the resource. We need to hide it for now, since all the data is imported. We're going to add it back once we start creating resources via the forms.
- [ ] Now that we have a details page for each resource, the user should be able to click the *title* and visit the details

**Comment by martinchristov** [comment]
not sure what the second task would mean @iperdomo . we already link to the details page of each resource

**Comment by iperdomo** [comment]
When clicking the *title* of each item, the user navigates to the detail page of the item
![2021-02-17_1568x347](https://user-images.githubusercontent.com/178474/108208679-a160b700-7129-11eb-928a-3cea2f5946ce.png)

**Comment by martinchristov** [comment]
ah thanks. I was confused because I didn't immediately understand which items in the footer you were referring to.
Actually by design we have a `Learn more` button so I'll just re-enable that.
