### ISSUE TITLE
Action to see the details from the browse view

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#106]
When visiting the *browse view* the user action to see the details of a particular resource is to click *anywhere* in the card (div).
According to feedback is not evident that is the action. They suggested a button/link with an action to see the details

**Comment by loicsans** [comment]
Adding a learn more button or link on each asset would really create noise and overwhelm the page. The idea would be to get a "learn more" button like on hover on each card. Visuals to come

**Comment by loicsans** [comment]
https://xd.adobe.com/view/6f0b4a6c-4a8c-4522-81cd-f2363d8d9bea-3a58/

**Comment by martinchristov** [comment]
Good compromise @loicsans
