### ISSUE TITLE
Redesign the interaction of the maps toggle/counts

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#107]
![2021-02-17_626x567.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/4171a2b0-7043-4c28-af0c-c7f303324bc9)

**Comment by loicsans** [comment]
https://xd.adobe.com/view/bc710834-c5d0-44b0-8e09-c02a8aafa061-e922/
Here is a suggestion
