### ISSUE TITLE
Comments Functionality 

### ISSUE THREAD

**Issue by kevinmugambi** [akvo/unep-gpml#1073]
- Only logged in users can comment
- Comments don't need any moderation/approval since we are tying comments to logged in users.
- Admins can delete comments
- E-mail Notifications: Resource owners get notified when someone comments on their resource.
- Users can udpate comments they have made.

**For Further Discussion**
- Should all admins get email notifications for all comments? Might be too many emails 
- Is there a way to automatically filter vulgar comments and flag/delete them?

Link to figma file:

**Comment by lucassousaf** [comment]
@kevinmugambi regarding what we already know, when we say resource we mean: Policy, Event, Resource, Initiative, Technology. Or just Resouce (financial_resource, technical_resource and action_plan)?

**Comment by kevinmugambi** [comment]
@lucassousaf we mean all resources (Policy, Event, Financing, Technical resources, Initiative, Technology, Action plan) on the platform.

**Comment by lucassousaf** [comment]
Ok thanks!
