### ISSUE TITLE
Convert non-member org to member if it exist on sign up

### ISSUE THREAD

**Issue by lucassousaf** [akvo/unep-gpml#1147]
When signing up someone might type an Entity name that already exists. If the already existing organisation is a `non-member-organisation` then we need replace it with the new details and set it to member.

**Comment by navins94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Non member sign up flow](https://trello.com/c/R6PVARZl/22-non-member-sign-up-flow)
