### ISSUE TITLE
Update the details show for activity shown in the browse (summary) view

### ISSUE THREAD

**Issue by joycarpediem** [akvo/unep-gpml#119]
Activities should not have the description showing. Only Title, Organisation and Geographical Info.

**Comment by dlebrero** [comment]
Still to do Fields "AO" "AP" "AQ" of:

LEGISLATION, STANDARDS, RULES: Column P, Q. Column AO, AP, AQ if the activity type was selected.
WORKING WITH PEOPLE: Column R, S, T, U, V, W, X. Column AO, AP, AQ if the activity type was selected.
