### ISSUE TITLE
/endpoints

### ISSUE THREAD

**Issue by martinchristov** [akvo/unep-gpml#12]
a single endpoint to return all data types (events, resources, policies, etc)
optional params for filtering:

- src // string to search in title
- type // enum(event, resource, policy...)
- country // iso-2

to be further developed later on

**Comment by iperdomo** [comment]
* `/landing`
```javascript
{"map": [{"country": "es", "project": 4, "resource": 5, "policy": 10, "event": 2}, {"country": "fr", "project": 4, /**/}}
 "topics": [{"type": "resouce"}, {"type": "policy"}, {"type": "event"}]
``` 
This is just a draft
