### ISSUE TITLE
Add disclaimers

### ISSUE THREAD

**Issue by joycarpediem** [akvo/unep-gpml#127]
Add Beta Disclaimer (on top of the home page)
Text: The GPML Digital Platform Phase 1 is now live and currently a Beta Version. Help us test the platform and let us know what you think at unep-gpmarinelitter@un.org. Take part in shaping the platform’s next releases, until its final launch scheduled for 2023. Stay tuned!

Add Content Disclaimer (top of the search result page)
Text: UNEP shall not be liable for third party content hosted on the platform. Contact us if you have any concerns with the content at: unep-gpmarinelitter@un.org. Please note that during Beta Testing, content and functionality issues may persist.

**Comment by loicsans** [comment]
https://xd.adobe.com/view/1e47a3ab-ad35-49c1-9ce4-0e3a1157325e-4b14/
