### ISSUE TITLE
Remove hard-coded GCP bucket name

### ISSUE THREAD

**Issue by lucassousaf** [akvo/unep-gpml#1310]
We shouldn't hard-code the app's configuration variables. At the moment the GCP bucket name is [hard-coded](https://github.com/akvo/unep-gpml/blob/main/backend/src/gpml/constants.clj#L29) and looks like we are using the same bucket in every environment. We should add that configuration to the `config.edn` and pass it properly to the places where we need the bucket name information.

**Comment by lucassousaf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove hard-coded GCP bucket name](https://trello.com/c/tH9a3kXy/122-remove-hard-coded-gcp-bucket-name)

**Comment by MichaelAkvo** [comment]
# Tasks:

## Backend

 - Migration script
    - `akvo-unep-gpml` bucket becomes prod
    - `akvo-unep-gpml-test` become test bucket
 - Move bucket-name to env variable
 - Add bucket name env variable to docker-compose
 - Mount directory with future service account in docker-compose `./credentials:/credentials`


## Devops
 
 - Create buckets:
   - `akvo-unep-gpml[-test|-dev]`
 - Create service accounts for new buckets
 - Add bucket name env var to `deployment.template.yml`
