### ISSUE TITLE
Investigate Åland Island showing as country

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#137]
In the landing page, the main map shows *Åland Island*
![2021-03-01-141105_1920x1080_scrot.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/f463420d-40b8-4576-80f1-e12229f0bdf0)

In the browse view, only *Åland*
![2021-03-01-141117_1920x1080_scrot.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/aefbe748-8952-4796-abe4-839177d13a97)

According to UNEP  Åland Island belongs to Finland. Can we check the GeoJSON?

**Comment by dedenbangkit** [comment]
investigation sent via zulip

**Comment by iperdomo** [comment]
Those islands are no longer in the [country.json](https://github.com/akvo/unep-gpml/blob/6662fb3c41c8c2aa9e57e57a5063025d63b3f587/backend/dev/resources/files/countries.json) , why?
