### ISSUE TITLE
Show all details of stakeholder in Admin view

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#139]
An admin should see all the details that the stakeholder (Individual) has entered in the registration form.

**Comment by loicsans** [comment]
https://xd.adobe.com/view/c552b9d8-220b-4b63-976a-185089c25e67-9001/

**Comment by iperdomo** [comment]
@wayangalihpratama we're still showing all the countries when the geo coverage is *Global*
![2021-03-17_1260x716.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/280f079f-d530-4b91-9a2d-85443a019f6b)
