### ISSUE TITLE
Remove country-list dependency

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/unep-gpml#142]
@wayangalihpratama 
remove everything that depends on `"countries-list": "^2.6.1"` and just use the country endpoint

- [x] src/modules/signup/comp/geo-coverage-input.jsx|5 col 28| import { countries } from "countries-list";
- [x] src/modules/signup/comp/geo-coverage-input.jsx|6 col 28| import countries2to3 from "countries-list/dist/countries2to3.json";
- [x] src/modules/signup/signup-form.jsx|14 col 28| import { countries } from "countries-list";
- [x] src/modules/signup/signup-form.jsx|15 col 28| import countries2to3 from "countries-list/dist/countries2to3.json";
- [x] src/modules/details/view.jsx|17 col 39| import { languages, countries } from "countries-list";
- [x] src/modules/details/view.jsx|19 col 28| import countries3to2 from "countries-list/dist/countries3to2.json";
- [x] src/modules/browse/view.jsx|15 col 28| import { countries } from "countries-list";
- [x] src/modules/browse/view.jsx|16 col 28| import countries2to3 from "countries-list/dist/countries2to3.json";
- [x] src/modules/events/form.jsx|7 col 39| import { languages, countries } from "countries-list";
- [x] src/modules/events/form.jsx|8 col 28| import countries2to3 from "countries-list/dist/countries2to3.json";

FYI, root already have country data from the backend, you only need to pass it

**Comment by iperdomo** [comment]
@wayangalihpratama let's remove the code instead of just comment it out
