### ISSUE TITLE
Refactor permissions system

### ISSUE THREAD

**Issue by lucassousaf** [akvo/unep-gpml#1530]
The analysis of the needs for the refactor of the permissions system and the implementation details are included in an attached document in the issue: [Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/10267350/Analysis.of.permissions.system.refactor.pdf)

[Here](https://raw.githubusercontent.com/gethop-dev/rbac/d9e812af2bca265fbc44d56692492a89a7654139/doc/arch/database_schema_adr-002.svg) we can also check the DB model for the Rbac permissions system.

Manual steps needed to do in test and prod envs:

- Install `uuid-ossp` extension in each DB, so we can generate random uuids from SQL directly.

**Comment by joseAyudarte91** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor of permissions system](https://trello.com/c/0VbRJQKJ/312-refactor-of-permissions-system)

**Comment by joseAyudarte91** [comment]
We have updated the document with the "analysis of the permissions system refactor".
[Technical_overview_and_RBAC_model_definition_as_of_10_07_2023.pdf](https://github.com/akvo/unep-gpml/files/12004376/Technical_overview_and_RBAC_model_definition_as_of_10_07_2023.pdf)

**Comment by joseAyudarte91** [comment]
We have made some corrections related to the `project` entity and the removal of not needed Comments-related additional permissions, attached in the last version of the document below:
[Uploading Analysis of permissions system refactor.pdf…]()

**Comment by joseAyudarte91** [comment]
Added another correction to the `project` entity-related permissions.
[Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/12067979/Analysis.of.permissions.system.refactor.pdf)

**Comment by joseAyudarte91** [comment]
Added missing permission to list assigned reviews for a user.
[Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/12097844/Analysis.of.permissions.system.refactor.pdf)

**Comment by joseAyudarte91** [comment]
Adjusted some permissions and their assignments in the last version of the document.
[Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/12172016/Analysis.of.permissions.system.refactor.pdf)

**Comment by joseAyudarte91** [comment]
Updated document again to reflect the inclusion of new permissions for non-published resources, assigned to some roles.
[Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/12184632/Analysis.of.permissions.system.refactor.pdf)

**Comment by joseAyudarte91** [comment]
Updated document to remove 2 permissions from a role.
[Analysis of permissions system refactor.pdf](https://github.com/akvo/unep-gpml/files/12197287/Analysis.of.permissions.system.refactor.pdf)
