### ISSUE TITLE
Transnational UI list

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#191]
Initial mock-ups of the new transnational UI filter:

https://xd.adobe.com/view/bc710834-c5d0-44b0-8e09-c02a8aafa061-e922/

**Comment by loicsans** [comment]
@martaotto, sorry I missed your message on teams.  Anyway, following your feedback, I suggest an improvement to the design as follow: 
https://xd.adobe.com/view/06fdb38e-2dae-4870-a030-e15c185e68e0-53ae/

**Comment by martaotto** [comment]
Hi Loic, thanks! This looks great. Do you mind making the update to the latest design, so it won’t confuse others when I ask for their approval?

Bests, Marta

From: Loïc Sans ***@***.***>
Reply to: akvo/unep-gpml ***@***.***>
Date: Tuesday, 20 April 2021 at 14:35
To: akvo/unep-gpml ***@***.***>
Cc: "Marta Ottogalli(Affiliate)" ***@***.***>, Mention ***@***.***>
Subject: Re: [akvo/unep-gpml] Transnational UI list (#191)


@martaotto<https://github.com/martaotto>, sorry I missed your message on teams. Anyway, following your feedback, I suggest an improvement to the design as follow:
https://xd.adobe.com/view/06fdb38e-2dae-4870-a030-e15c185e68e0-53ae/

**Comment by martaotto** [comment]
Hi Loic,

This is to follow up on the question below. Also, Caroline has submitted the UI list to be viewed through the “i” button.  I don’t see that implemented in the design you shared. I think it makes sense to have it in there already.

Bests,
Marta

From: "Marta Ottogalli(Affiliate)" ***@***.***>
Date: Tuesday, 20 April 2021 at 14:37
To: akvo/unep-gpml ***@***.***>, akvo/unep-gpml ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [akvo/unep-gpml] Transnational UI list (#191)

Hi Loic, thanks! This looks great. Do you mind making the update to the latest design, so it won’t confuse others when I ask for their approval?

Bests, Marta

From: Loïc Sans ***@***.***>
Reply to: akvo/unep-gpml ***@***.***>
Date: Tuesday, 20 April 2021 at 14:35
To: akvo/unep-gpml ***@***.***>
Cc: "Marta Ottogalli(Affiliate)" ***@***.***>, Mention ***@***.***>
Subject: Re: [akvo/unep-gpml] Transnational UI list (#191)


@martaotto<https://github.com/martaotto>, sorry I missed your message on teams. Anyway, following your feedback, I suggest an improvement to the design as follow:
https://xd.adobe.com/view/06fdb38e-2dae-4870-a030-e15c185e68e0-53ae/
