### ISSUE TITLE
Wrong number of pages when using Bookmarks/Favorites flag

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#201]
The result only shows 1 resource, but we have access to several pages. Clicking those page links show zero results.

![2021-04-27_1657x518.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/bf9199b5-f7f6-41db-a8b5-a77a1c37d404)

**Comment by martaotto** [comment]
This issue is exactly the same issue that I pointed out in ticket in ticket #218

**Comment by martaotto** [comment]
pagination still not working for individuals

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/73257aa2-86aa-4e2b-8ce2-f3d1740384cb)
