### ISSUE TITLE
Dropdown showing list on top

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#214]
There are several places where the `Select` component shows the list of items on top, even if there is more than enough space to show it at the bottom.
Showing the list of items on top makes sense if the control is at the bottom border of the page and there is no vertical space left.

![2021-05-03_1537x881.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/6588466c-5b74-47bf-8e1b-01e728b8ed05)

**Comment by wayangalihpratama** [comment]
Hi @iperdomo , 
What was the browser version you used to test it? 
Because it works fine here

**Comment by iperdomo** [comment]
Chrome / Windows 10 / Screen: 1366 x 768 - You can use BrowserStack to test it

**Comment by iperdomo** [comment]
The same applies to Part 3 - Question 32
![2021-05-05_1152x570.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/88c54221-45a9-4654-978f-8798dba427eb)
