### ISSUE TITLE
Filter sidebar + pagination needs to be anchored when scrolling up and down on the ressources results page

### ISSUE THREAD

**Issue by loicsans** [akvo/unep-gpml#218]
Also it'd be good to limit the number of assets per page to max 15 ressources

**Comment by loicsans** [comment]
@wayangalihpratama please let's discuss when you get to that

**Comment by dedenbangkit** [comment]
@loicsans please review

**Comment by iperdomo** [comment]
When changing the filter (e.g. adding/removing an additional resource type) the scroll position remains at the same position, leading to *strange* behavior, e.g. not looking at the full list result, but just the last item.

IMHO, when the user changes the filter, we need to reset the scroll position to the top. Please coordinate and agree with  @loicsans ?

https://images.zenhubusercontent.com/326952490/a4e021ce-fc0e-4303-a114-1a739e75a701/unep_2021_05_20_17_48_29.mp4

**Comment by martaotto** [comment]
I am reopening this issue and moving it to: in progress

A similar bug to the one pointed out by ivan. Pagination is not adapting to the search results.

https://images.zenhubusercontent.com/326952490/fd5adea8-2170-49a7-a6c3-3832046ef4ee/whatsapp_video_2021_05_25_at_15_02_12.mp4
