### ISSUE TITLE
/api/tag

### ISSUE THREAD

**Issue by martinchristov** [akvo/unep-gpml#22]
returns available tags to be used in creation of new event as well as in /browse filters

**Comment by iperdomo** [comment]
Current idea: `/tag/{topic-name}` - Where `{topic-name}` ~ `policy|technology|event|policy|resource`

**Comment by punchagan** [comment]
`/api/tag/event` returns the tags to be used for events. 
`/api/tag/<topic-name>` works in some cases, but not all the cases, since the tag categories are not named consistently. We can create a mapping for the other topics, once we have more clarity on these tags, and when we need them.
