### ISSUE TITLE
Change to multi-select options

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#221]
Questions 16, 18, 20 must be *muti-select* option. There are usually many entities involved for each initiative.

![2021-05-06_565x402.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/ab32d659-0a1a-47be-86a7-d720532dc275)

**Comment by wayangalihpratama** [comment]
I think this change also needs some change on the backend. I try to update the question schema to support multiple and Submit, that works fine. But the data for questions 16, 18, 20 doesn't appear on the admin preview.

**Comment by martaotto** [comment]
This ticket is incomplete since the multi-select option needs to apply to other forms: ACTION PLANS, FINANCING RESOURCES TECHNICAL RESOURCES FORM (entity, donor and partners) - please make this donor and partners field optional

**Comment by martaotto** [comment]
I will move this ticket to in progress:

This ticket is incomplete since the multi-select option needs to apply to other forms: ACTION PLANS, FINANCING RESOURCES TECHNICAL RESOURCES FORM (entity, donor and partners) - please make this donor and partners field optional
