### ISSUE TITLE
Show all details in Admin section

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#225]
Once a resource or stakeholder is approved, an Admin can't see all the details.

**Comment by martaotto** [comment]
I will reopen 

This is still wrongly showing in the Admin view

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/64c20aae-df95-4fcd-bb92-eb5a7bf372a3)

**Comment by iperdomo** [comment]
@punchagan offering/seeking tags are shown in `tags` section. @wayangalihpratama has done a change in the details page to separate those.

**Comment by wayangalihpratama** [comment]
On the details page, `tags`, `seeking`, and `offering` is separated from BE.
