### ISSUE TITLE
Make Map Key Clickable Again (UI Inconsistency)

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#226]
![Picture 1.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/5fd539f6-ac70-4e8f-8a1b-cefa9ff2d532)

Since the map changes where implemented this is no longer clickable.

**Comment by iperdomo** [comment]
Why is not possible to highlight the ones with value `0` ?

https://images.zenhubusercontent.com/326952490/dcfd72dc-fd48-4b74-ad1a-8e17e78a7c49/unep_2021_05_20_17_57_53.mp4

**Comment by dedenbangkit** [comment]
Sure, @loicsans also said that 0 should also clickable
