### ISSUE TITLE
Blurred and extremely large Individual Profile Image

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#228]
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/c2e2de67-4c25-493a-959f-b0d4e3495d48)

Make sure it is not blurred. It should reflect initials. it should be much smaller. Apply changes to all individual profiles.

**Comment by dedenbangkit** [comment]
@wayangalihpratama, I made some changes, please check

**Comment by dedenbangkit** [comment]
maybe better to use regex
![Screen Shot 2021-05-24 at 11.26.03.png](https://images.zenhubusercontent.com/600c532b852e9f29c0227e40/7c249d94-57cf-4368-9dba-6d9cc32a9f29)

**Comment by martaotto** [comment]
I am reopening this issue:

All these are still blurred:
https://digital.gpmarinelitter.org/stakeholder/10040
https://digital.gpmarinelitter.org/stakeholder/10033
https://digital.gpmarinelitter.org/stakeholder/10031
https://digital.gpmarinelitter.org/stakeholder/10026
https://digital.gpmarinelitter.org/stakeholder/10023
https://digital.gpmarinelitter.org/stakeholder/10020
https://digital.gpmarinelitter.org/stakeholder/10020
https://digital.gpmarinelitter.org/stakeholder/10007
https://digital.gpmarinelitter.org/stakeholder/10005
https://digital.gpmarinelitter.org/stakeholder/41

Profile not working at all: https://digital.gpmarinelitter.org/stakeholder/10004

also why are some showing two letter and other one letter? it should be standardized.
One letter example: https://digital.gpmarinelitter.org/stakeholder/10001

Broken image: https://digital.gpmarinelitter.org/stakeholder/10038

Now to solve for that problem the individual profiles look completely different from the entities, they are skewed to the left.

**Comment by iperdomo** [comment]
We're going to use a default user image/icon for all stakeholders that have not uploaded a profile image

**Comment by iperdomo** [comment]
@loicsans we're waiting for the default profile image to be used.

**Comment by loicsans** [comment]
![profile-pic-not-found](https://user-images.githubusercontent.com/1717219/121059546-416e4900-c7ca-11eb-8d56-66445412ce19.png)

**Comment by GeertSoet** [comment]
Proposal: include as part of Ph. II release while waiting for larger overhaul of individual page.

**Comment by GeertSoet** [comment]
@navins94 assigning this to you, please have a look :)

**Comment by tangrammer** [comment]
BE CODE: https://github.com/akvo/unep-gpml/blob/main/backend/src/gpml/handler/stakeholder.clj#L177

let's try 
```
For Auth0 can we add this URL - https://ui-avatars.com/api/?size=480&name=Navin+Shingote for if there is no image
```
as @navins94 asks

**Comment by tangrammer** [comment]
<img width="910" alt="Screenshot 2021-11-22 at 18 06 18" src="https://user-images.githubusercontent.com/731829/142904281-99b7124e-a749-443c-be1b-24277842697e.png">
