### ISSUE TITLE
Rebuild GeoJSON for landing map

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#23]
The GeoJSON used for the map has been *compressed* too much and lost details. Some countries are not there anymore.

**Comment by iperdomo** [comment]
![2021-01-21_880x548.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/0f28310b-b904-4857-9b8c-060f898c22b0) Picasso like :thinking:

**Comment by iperdomo** [comment]
Not for now, but in the future we could compress it with something like (Geobuf)[https://github.com/mapbox/geobuf]. Again, we don't need to optimize the file right now.

**Comment by dedenbangkit** [comment]
Please approve and close @iperdomo :)

**Comment by iperdomo** [comment]
On an empty cache, depending of the network it takes almost 6s to *start* the application

```
12 requests
12.76 MB / 4.31 MB transferred
Finish: 5.70 s
DOMContentLoaded: 5.11 s
load: 5.53 s
```
I did a quick check and using `Geobuf` we reduce the size of the data from 9.77 MiB to 1.61 MiB

I'll close this issue for now and open a new one for a later optimization
