### ISSUE TITLE
URL UI (UI Inconsistency)

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#230]
Change the URL UI in all forms to look like the event one. 

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/abd97a67-4988-4fb3-a911-e481f585bccd)
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/a41003e5-8c1b-4844-9fe3-a67a13faf21b)

**Comment by wayangalihpratama** [comment]
URL validation
