### ISSUE TITLE
Policy Submission Error

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#235]
Policy submission is not working. Please note that they should be able to submit and receive a message notify them that they submissions will be reviewed before it can be included.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/896cbcc0-3345-4581-a61e-a18d032f5a34)

**Comment by iperdomo** [comment]
@dedenbangkit I found a couple of extra issues. 

* Now that the `Submit` button is *fixed* the *Thank you ...* message is hidden, the user needs to scroll top to see it.
* After submitting a Policy, you can create a new Policy right away. See the problems in the attached video.
https://images.zenhubusercontent.com/326952490/aba2e821-ba72-44d0-a9af-caace0e68594/unep_2021_05_20_17_15_20.mp4
