### ISSUE TITLE
Resources Validation Error + Delete Test Resources

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#236]
Sarah got an approval request in my email for the TEST event but not for initiative, action plan, policy, technical resource, financing resource and technology.

Remove “test” from the resources uploads (Sara’s test requests). Delete the actual resources too.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/c3bcc367-f15b-4d51-996e-b874e67f487a)
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/e11afb3e-721e-4bf0-83fa-0a8a98d260a0)

**Comment by martaotto** [comment]
@iperdomo could you please prioritise deleting the test resources? This were created by Sarah to test the forms, but they should be removed.

**Comment by dedenbangkit** [comment]
![Screen Shot 2021-05-18 at 20 29 07](https://user-images.githubusercontent.com/3245109/118659715-c4c5fb80-b817-11eb-967a-19732c5c80d3.png)

@iperdomo : rows deleted (cascade)

```SQL
DELETE FROM technology where LOWER(name) LIKE '%tes%' and id > 10000;
DELETE FROM resource where LOWER(name) LIKE '%tes%' and id > 10000;
```
