### ISSUE TITLE
Align and Improve form Buttons UI

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#237]
It should be indent on the right not on the left. 

UI should be improved to show they are actual buttons.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/83a8e1bd-6685-4e4d-8c1a-5c84ad53aa1d)

**Comment by loicsans** [comment]
![Screenshot 2021-05-18 at 15.15.14.png](https://images.zenhubusercontent.com/5cc0217556993227e2467464/daf5f243-a2fb-44f5-af56-7a96f3b07bc0) 
This is as per my original sketches, the items were supposed to feel like buttons.
