### ISSUE TITLE
Initiative: questions numbering (UI inconsistency)

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#238]
The sub-types of initiative numbering should be 4.1, 4.2, 4.3
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/85fb70a4-0bef-47be-b1f0-6760e25d966b)

**Comment by iperdomo** [comment]
The proposal is to remove all numbering. Numbers in forms are for printed ones, where you have instructions to follow manually to a different part of the form (e.g. if you answer "Yes" to question 4.1, move to 4.1.1).

A common mistake in digitizing existing forms is to attempt to translate the *analog* world to a *digital* one. Question numbers make little sense (offer little value) to end users filling the form.

@martaotto do you agree to remove all numbers from question texts?

**Comment by iperdomo** [comment]
@martaotto do we have an agreement on removing the numbers?

**Comment by iperdomo** [comment]
Confirmed via email with @martaotto that we're going to remove the question numbers
