### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#241]
Floating box often shows at the top with this UI. This is a common bug. Is there a way we can prevent this?!

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/75259591-2637-4211-aeae-31d9476158b3)

**Comment by wayangalihpratama** [comment]
This is the same issue with https://github.com/akvo/unep-gpml/issues/214
And that was closed.
