### ISSUE TITLE
Currency Field (UI Inconsistency)

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#242]
Make Currency UI consistent. Can we have the currency included in the grey box as a dropdown?
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/154861d3-0bea-4edc-bbf6-f23c2dcc0d9f)

**Comment by iperdomo** [comment]
We won't include the currency as part of the dropdown. From the data point of view, the value and the currency are 2 different fields.
