### ISSUE TITLE
Loading spinner is not longer centered

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#252]
The *Loading...* message and spinner was centered, now it shows aligned top left, next to the filter box
https://images.zenhubusercontent.com/326952490/ebf8684e-d8ea-4e0e-822a-2415ab0c498a/unep_2021_05_20_17_24_13.mp4

**Comment by dedenbangkit** [comment]
https://github.com/akvo/unep-gpml/commit/7e67ef7edc0f97a348d6c284cd7ff7873f2fee18
