### ISSUE TITLE
Background moves if you use the Highlight required fields toggle

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#256]
https://images.zenhubusercontent.com/326952490/2fad6860-6509-462c-a320-f684ac76f911/unep_2021_05_21_17_36_48.mp4

**Comment by wayangalihpratama** [comment]
I think this issue was completed by mas @dedenbangkit 
https://github.com/akvo/unep-gpml/commit/65a183b368004c4a11a5de98f0ff90c312c95cf0
