### ISSUE TITLE
Adding placeholder images to Initiatives

### ISSUE THREAD

**Issue by irenewestra** [akvo/unep-gpml#268]
We need to add placeholder images for Initiatives that do not have an own image. Images are based on 'Type of action':

- Legislation, standards, rules
- Monitoring and analysis 
- Technology and processes
- Working with people

![legislation.jpg](https://images.zenhubusercontent.com/604b12ea02390db1b594f304/0b5ed83f-a039-48f2-a83b-8fb8181eb05b)

![Monitoring.jpg](https://images.zenhubusercontent.com/604b12ea02390db1b594f304/e15b8d11-8648-43ca-b45b-221785dfb608)

![Technology.jpg](https://images.zenhubusercontent.com/604b12ea02390db1b594f304/76055d96-79d9-414e-95d2-cd9d68bf216b)

![Workingwithpeople.jpg](https://images.zenhubusercontent.com/604b12ea02390db1b594f304/c4bac868-958d-4445-9dc4-487d9385b4c0)

**Comment by GeertSoet** [comment]
@irenewestra the first image seems to have a very small resolution, could you check?

**Comment by irenewestra** [comment]
@GeertSoet I have moved this ticket to the Icebox (for now), since UNEP replied: "At this stage (since we have editing rights) let’s discuss this as part of the UX/UI style redesign"
