### ISSUE TITLE
Import latest dump file 2021-05-25

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#269]

**Comment by dedenbangkit** [comment]
Currently, there are four types of organisation list:
1. Organisation from [GPML Members 2021-03-29](https://docs.google.com/spreadsheets/d/1Tm4UfpZ9aGRJrM4RlELjhfHA1BZJs9Rq/edit#gid=2024822887). We use Member ID column as id for this list.
2. Organisation that comes from other resources (e.g policy, technology, resource technolgy, etc) that are unlisted in above (point number 1), the id started from **1001**.
3. Organisation lists that comes from [tc.akvo repo](https://github.com/akvo/akvo-tech-consultancy/blob/sites/unep-dashboard/sites/unep-dashboard/database/transformer/organisationlist.csv), we merged the id to above list, so id started from *1001**.
4. Organisation that user submitted in prod db, the ids are started from **10001**.

**Comment by punchagan** [comment]
We are going to get a new dump, and we don't need to try to get this dump file imported.
