### ISSUE TITLE
Update Admin View

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#271]
1. Status column and other columns under admin should allow sorting eg alphabetically, most recent etc
2. Have categories for approved and rejected requests in the admin. Only show the pending requests as a list. The approved and the declined requests can be a drop down list.
3. The approved resources in the admin should show the name of the person that approved the resource.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/221023c5-d9d7-40a7-a8a6-1b28d75b3264)

**Comment by GeertSoet** [comment]
Closing this ticket as it will be handled as part of wf3 [#358](https://app.zenhub.com/workspaces/unep-gpml-60095b9be2afac00115fd0d6/issues/akvo/unep-gpml/358)
