### ISSUE TITLE
Toggles on Map

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#272]
Turn off toggle when clicking on another toggle. Enable two toggles on at the same time.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/52b5aecf-eca3-485f-9342-5988b1958b3c)

**Comment by GeertSoet** [comment]
To confirm, we want to be able to have for example action plans and policy acivated here at the same time?

**Comment by GeertSoet** [comment]
Closing this issue for now due to more rigorous changes coming up in the resources overview page.
