### ISSUE TITLE
Import New Country Group

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/unep-gpml#280]
- [x] Create migration to change the initiative value q24_1
- [x] Change `q24_1` in FE with this format `[{"country_group_id":"country_group_name"}]` (e.g [{"1":"Africa"}])
- [x] Create `new_country_group.json` along with `country_group_map.json`
- [x] Create country_group_updater with revert support
- [x] Create `yml` template for kubernetes jobs

**Comment by dedenbangkit** [comment]
@iperdomo @punchagan 

So far, we have a [map of old to new country group id](https://github.com/akvo/unep-gpml/blob/280-import-new-country-group/backend/dev/resources/files/new_country_groups_mapping.json).

We need to inform UNEP that:

- We have tried different method to match the [old country group list](https://github.com/akvo/unep-gpml/blob/main/backend/dev/resources/files/country_group.json) and [new country groups list](https://docs.google.com/spreadsheets/d/1zeWnuKsclWILw-LBltuE2q8glsjqg_vE/edit). As the result, we matches we still have 88 more country groups which not listed in the [latest excel file](https://docs.google.com/spreadsheets/d/1zeWnuKsclWILw-LBltuE2q8glsjqg_vE/edit), currently we [moved the ids to +1000](https://github.com/akvo/unep-gpml/blob/946f8034e935b05dd298a9f97bc2eb641318cb07/backend/dev/resources/files/country_group-new.json#L282-L904)
- There are duplicated id for [country group id number 30](https://docs.google.com/spreadsheets/d/1zeWnuKsclWILw-LBltuE2q8glsjqg_vE/edit#gid=838517012&range=33:34), so we changed id 30 to the end of rows.
- We don't have UI Labels for the unlisted country groups, so we use it's default name as label.
- We also don't have category / group (**UN Regional Groups of Member States, Regional Seas, etc**)  for the unlisted, we leave it null.

Unlike updating country, the current strategy for country group is force update all the data related to country group with migration instead of doing it several times, so revert parameter is not relevant for this update. Once we have the stable country group id, then UNEP will follow the id that we are using in the database if there any changes.


https://github.com/akvo/unep-gpml/blob/280-import-new-country-group/doc/new%20country%20groups%20script.ipynb

**Comment by GeertSoet** [comment]
@punchagan do you know what this is about and where we're at?

**Comment by dedenbangkit** [comment]
Hi @Geerts & @punchagan, I have documented the steps here: https://github.com/akvo/unep-gpml/blob/main/README.dev.md#generate-countries-list--id-mapping
