### ISSUE TITLE
New Resources upload for entities that are not in the list of GPML Membrs

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#283]

**Comment by martaotto** [comment]
Currently when adding a new resource the Platform only allows to choose from entities that are part of the GPML members list. Instead in the forms it should be possible to add a new entity that it might not be part of the list.

**Comment by GeertSoet** [comment]
Currently it is possible to add an entity through selecting "other". Is this sufficient for now or can we close this?

I would propose to change "other" to  "create new entity".

**Comment by punchagan** [comment]
Yes, Galih already worked on making the other option easier to find, which wasn't the case when this issue was created. This can be closed now. We can tackle the rename as a separate ticket, after agreeing on the wording with UNEP.
