### ISSUE TITLE
Other field not showing in "part 5 funding"

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#348]
When user selects other in the first question, the other field does not show up. 

* https://unep-gpml.akvotest.org/add-initiative

![Screenshot 2021-07-19 at 13.59.18.png](https://images.zenhubusercontent.com/55d493ca4f7a08fbb7f464b2/82fabb7f-3f73-432c-b3fb-7f65bab9accd)

**Comment by punchagan** [comment]
This has now been fixed. 

The details page should probably show the content in the text field in a parenthesis or something, but there are other fields that also need to be displayed correctly. We can tackle this in a separate issue.
