### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#362]
Questions
- Where do the "read more" buttons redirect to? 

**To do** 

- [ ] UNEP: provide final copy, images and documents (1)
- [ ] Design: Loic small validation (1)
- [ ] Frontend: start after validation
- [ ] Backend: little needed

**Comment by loicsans** [comment]
I have already updated the text with the latest one. I actuall created a new issue, it's now just waiting to be merged: https://github.com/akvo/unep-gpml/pull/411
