### ISSUE TITLE
User email verification on test error

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#415]
localhost:3001/?supportSignUp=true&supportForgotPassword=true&message=Your email was verified. You can continue using the application.&success=true&code=success

**Comment by punchagan** [comment]
This has probably already been fixed by changing the order of call back URLs in Auth0. See [this](https://akvo.zulipchat.com/#narrow/stream/270426-unep/topic/Data.20Hub/near/251513207). @tangrammer can you check whether that makes sense, and close the ticket, if it does.
