### ISSUE TITLE
Admin page backend

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#478]
To do
- [x] Multiple reviewers

- [x] Split calls resources and stakeholders so we can show them separately 

- [x] We also need `image url` to show on new request / request archive list & search feature (design reference https://www.figma.com/file/uxm2soK24P4EuiPgLuUJjK/GPML?node-id=357%3A574)

**Comment by GeertSoet** [comment]
- [ ]  Multiple reviewers 
- [ ] Split calls resources and stakeholders so we can show them separately
- [ ] We also need image url to show on new request (design reference https://www.figma.com/file/uxm2soK24P4EuiPgLuUJjK/GPML?node-id=357%3A574)
- [ ] request archive list & search feature

**Comment by tangrammer** [comment]
@GeertSoet  could you expand this one => "request archive list & search feature (Juan)"  ?

**Comment by GeertSoet** [comment]
> @GeertSoet could you expand this one => "request archive list & search feature (Juan)" ?

These are the filters and search

**Comment by GeertSoet** [comment]
Feedback testing: 

- [ ] search undo not working

- [ ] Hide tags tab

- [ ] Filter by declined> the label on the top should also be rejected (instead of declined)

- [ ] Assign owner checkbox, limit max width 

- [ ] Amount of items per page selector is not working

I didn't test the ownership part functionality yet, let me know when I can.

**Comment by tangrammer** [comment]
authorization based on ownership added to CRUD resources
