### ISSUE TITLE
Good to have - Show counts next to resources in brackets so that the user is aware of the volume of content based on the country filter

### ISSUE THREAD

**Issue by joycarpediem** [akvo/unep-gpml#48]

**Comment by joycarpediem** [comment]
<img width="357" alt="Screenshot 2021-02-10 at 7 28 04 PM" src="https://user-images.githubusercontent.com/4419787/107507142-1a1bbc80-6bda-11eb-8678-235056ba5d5f.png">
I filter for a country but the count are still overall @punchagan

**Comment by punchagan** [comment]
argh, I missed the based on country filter part. I'll fix this.

**Comment by iperdomo** [comment]
I'll close this for now and review it later
