### ISSUE TITLE
Missing log in prompt

### ISSUE THREAD

**Issue by irenewestra** [akvo/unep-gpml#551]
If an Admin receives an mail like _[UNEP GPML] New stakeholder/organisation/resource needs approval_ there's an URL directing the Admin to: https://digital.gpmarinelitter.org/profile. However, if you are **not logged in** the page keeps 'loading'. Would be good to direct the Admin to log in.

**Comment by tangrammer** [comment]
<img width="1109" alt="Screenshot 2021-11-04 at 09 18 48" src="https://user-images.githubusercontent.com/731829/140280256-7b22b914-52ea-438f-b6ff-b8b637803bfa.png">
