### ISSUE TITLE
Geocoverage - Transnational logic

### ISSUE THREAD

**Issue by irenewestra** [akvo/unep-gpml#561]
- [x] Enable option to select _multiple_ transnational country groups
- [ ] Add "Other" option in dropdown
- [ ] In case of "Other", show dropdown of countries and enable to select _multiple_ countries

**Comment by GeertSoet** [comment]
@navins94  frontend: 

- [ ] User should be able to multiple select transnational country groups.  Label = Geo Coverage (transnational)
- [ ] Next to this, when user selects transnational, in addition to the the multiple country groups, user should also be able to select stand alone.  Label = Geo Coverage (countries)
- [ ] When user selects geo coverage type = national, only allow ONE country to be selected.

forms will send (POST/PUT) any of these properties (geo_coverage_countries, geo_coverage_country_groups) depending following cases:

global: don't send any of these props
national: send geo_coverage_countries with only one country-id inside the vector. eg: {geo_coverage_countries:[1]}
transnational: could send both: eg: {geo_coverage_country_groups: [2,3], geo_coverage_countries:[1,5]}
:, with empty or not empty vector

**Comment by GeertSoet** [comment]
Testing 16th November.
