### ISSUE TITLE
Admin should be able to transfer ownership of resource

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#567]

**Comment by GeertSoet** [comment]
MVP

- [ ] In the edit page of a resource, show who is the current owner/author. 

- [ ] Admin or current should be able to transfer the ownership to other individuals

_In the future_ we can work on more advanced roles and permissions.

**Comment by tangrammer** [comment]
BE done

**Comment by GeertSoet** [comment]
@tangrammer let's think about the easiest way to get this functionality integrated into the FE
