### ISSUE TITLE
Individual entities should go to non member list 

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#569]
**Describe the bug**
We have noted that when someone signs up and inputs their entity(through the other option) the entity is shown as a GPML member on the platform. 
This entity instead should be added to the non-members' list since the stakeholder did not sign up on behalf of an entity other than as an individual.

Below are the links for the entity and stakeholder in  question.
https://digital.gpmarinelitter.org/organisation/10364
https://digital.gpmarinelitter.org/stakeholder/10169

Important to fix asap as it any new individual signing up will cause a wrong entry in the member list, which we then need to fix in the database.

**Comment by tangrammer** [comment]
fixed in prod

**Comment by tangrammer** [comment]
```
"CREATE OR REPLACE VIEW public.v_organisation_data AS
 SELECT o.id,
    o.name,
    o.url,
    o.logo,
    o.type,
    o.country,
    o.geo_coverage_type,
    o.program,
    o.contribution,
    o.expertise,
    o.review_status,
    o.created_by,
    geo.geo_coverage_values
   FROM (public.organisation o
     LEFT JOIN ( SELECT og.organisation,
            json_agg(COALESCE(og.country, og.country_group, 0)) AS geo_coverage_values
           FROM public.organisation_geo_coverage og
          GROUP BY og.organisation) geo ON ((o.id = geo.organisation)))
   WHERE o.is_member=true;
"
```

**Comment by tangrammer** [comment]
added `WHERE o.is_member=true;`

**Comment by GeertSoet** [comment]
Thank you Juan
