### ISSUE TITLE
Add "Communities" link to navigation pointing to discoure (external) 

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#570]
Connect stakeholders > Communities > 
URL = https://communities.gpmarinelitter.org

Should be added to production when possible.

**Comment by tangrammer** [comment]
@loicsans any ideas on where should we add this button?

**Comment by irenewestra** [comment]
Hi @tangrammer. Currently there is no separate button needed yet. The link can be added in the top navigation bar, under Connect Stakeholders. You can name it "Community".
