### ISSUE TITLE
Discourse auth0 

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#572]
- [x] Verify auth0 setup test/production. Will it work for now

- [ ] Define future steps to make sure we follow our normal development workflows with a test and production auth0 setup

**Comment by tangrammer** [comment]
@GeertSoet "Define future steps to make sure we follow our normal development workflows with a test and production auth0 setup" for that we need another discourse forum (and pay for it) so perhaps we can just stick with this one

**Comment by GeertSoet** [comment]
Let's do that, we don't need major development on it anyway at this moment and most is easily configurable via the editor.
