### ISSUE TITLE
Entity Sign Up - explore visual options

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#573]
- [ ] Make visually clearer in the prompt the distinction between "sign up" for a new account and "logging in" with an existing individual account

- [x] @tangrammer can you check what styling options we have in Auth0?

- [x] @loicsans can you propose a (simple) design?

**Comment by tangrammer** [comment]
Checked auth0 options to adapt UI
we have these configs available https://auth0.com/docs/libraries/lock/lock-configuration ... already added some logic to auth0 `test` env [login-page](https://manage.auth0.com/dashboard/eu/unep-gpml-test/login_page)
based on this [howto](https://community.auth0.com/t/how-do-i-redirect-users-directly-to-the-hosted-signup-page/42520)

```js
  if (config.extraParams && config.extraParams.action) {
      lockExtraParams.initialScreen = isSignup ? "signUp" : "login";
      lockExtraParams.allowLogin = isSignup ? false : true;
      lockExtraParams.allowSignUp = isSignup ? true : false;
    }

```

**Comment by tangrammer** [comment]
@loicsans available UI options are: https://auth0.com/docs/libraries/lock/lock-ui-customization

**Comment by GeertSoet** [comment]
@tangrammer I think we can take the new set up as mvp and continue styling in the future.

**Comment by GeertSoet** [comment]
@Sarah to provide transparent logo for auth0 popup.

**Comment by GeertSoet** [comment]
![auth-log.png](https://images.zenhubusercontent.com/55d493ca4f7a08fbb7f464b2/223ca613-5ebd-4a7d-887b-fcfdac0b6041)

@tangrammer could you add this logo to the auth0 popup? And what would be the steps to release this popup? Is it a matter of mirroring the settings on production?

**Comment by tangrammer** [comment]
Logo added to `test`
yes, we need to mirror the settings on auth0 production but also deploy main branch  changes

**Comment by GeertSoet** [comment]
And main branch on test is full of other changes right? UNEP is asking us if we can release this as they are making a guide. But that doesn't sound too promising:)
