### ISSUE TITLE
Flexible forms frontend

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#589]
To do 

1. Create static frontend with new interaction
2. Implement form for tech/financing resources
3. QA with Geert and partner 
4. Add additional resources
5. 2nd prio functionality such as automated tags and other funky stuff :) 

General comment

- All basic info  _option questions_ are mandatory, with the NA option listed as a way out.

**Comment by GeertSoet** [comment]
Endpoint: https://unep-gpml.akvotest.org/flexible-forms

**Comment by GeertSoet** [comment]
Akvo to do 
- [ ] The introduction text is not complete (the text continues on the next page in the Blueprint
- [ ] The next/previous buttons should be available in the bottom of the page 
<img width="244" alt="Screenshot 2021-12-07 at 14 45 51" src="https://user-images.githubusercontent.com/13728925/145040444-feea798e-3199-4cfb-a4ce-b34f6b5448c0.png">
- [ ] Please select other individuals that will support in managing the resource. --> Show full name
- [ ] Subcontent Options Definitions (info icon) are missing
- [ ] Basic info > In which country are you headquarters? > this isn't relevant while adding a resource
- [ ] Basic info > tags list is empty, check tags api to fill
- [ ] Basic info> Search for a GPML Member Entity > these should be a combined list of members and non members, and therefore the label should be different. > Also, it should be clear that this is the resource OWNER>  check with Loic. 
- [ ] Info and docs missing, add with basic text editor for now, add to wysiwyg when we have time. 

UNEP to do
- [ ] Provide wework url for getting started documents

**Comment by loicsans** [comment]
@navins94 here are the icons for the flex form:
[FlexForm-icons.zip](https://github.com/akvo/unep-gpml/files/7703025/FlexForm-icons.zip)

**Comment by loicsans** [comment]
Some visual improvements: 
It’d be good and more balanced to Increase padding of the top form bar to (padding: 20px 0;)
![Screenshot 2021-12-13 at 10 52 06](https://user-images.githubusercontent.com/1717219/145799118-9abfedd2-26d7-41d5-889c-4f8e08e03432.png)


The form nav is missing at the bottom of the form, it's part of the ux to facilitate form submission, is it complex to implement?
![Screenshot 2021-12-13 at 11 05 19](https://user-images.githubusercontent.com/1717219/145799070-522438a4-f0d0-44e0-a96a-f9e00b0a1654.png)


Form filling progress indicators and markings are missing. I would slightly dim the colours and simplify by using the space better,  if we can’t implement this right away: 
![Screenshot-2021-12-13-at-11 06 06](https://user-images.githubusercontent.com/1717219/145799214-d6a8f6d6-b19d-4a72-8fa0-8a9ab06bc834.jpg)


The icons needs tidying up, I have created a new set for Unselected / Selected states, with a totally new one for Financing resources. And I am attaching them as SVG directly in the github issue.
[FlexForm-icons.zip](https://github.com/akvo/unep-gpml/files/7703088/FlexForm-icons.zip)

**Comment by loicsans** [comment]
@navins94 This is how the location and geo-coverage section should be:
![Screenshot 2021-12-13 at 16 40 14](https://user-images.githubusercontent.com/1717219/145832471-8dd03218-cdb1-4189-9007-3379a199dbf7.png)

**Comment by navins94** [comment]
@loicsans Transnational will only have one option ? Or should we keep two like the way it is right now ?

**Comment by loicsans** [comment]
@navins94 you are correct:
![Screenshot 2021-12-13 at 17 14 01](https://user-images.githubusercontent.com/1717219/145837870-d8d1b47f-4bf9-4490-ad63-4372bd15f8c4.png)

**Comment by navins94** [comment]
Hi @diptigautam ,
We need to add one more key in policy to store topics

**Comment by GeertSoet** [comment]
- [ ] Info And Docs - Optional --> This is correct and should show under Documents and info in the detail page. 
- [ ] "Links to further information " --> This is obsolete and can instead will be replaced by related content.
- [ ] Add related content, max 4 internal links to platform, through "GPML resource nav/selector"

**Comment by GeertSoet** [comment]
- [ ] Hide see more (for example content)
- [ ] Implement initiative form
- [ ] Link to  Knowledge Exchange Library. > update once library overview has been merged
- [ ] Content type> Sub content> after selecting a sub content type, one can not unselect. Solve with cross?
- [ ] Full form> Optional> align fonts: larger font.
- [ ] Content type > Circle options aim is to have all options above the fold. Work together with Loic to solve.
- [ ]  label city under subnational  geocoverage should be 'subnational area'. Placeholder text: 'city, state , territory...' 
- [ ] Image/banner: it's either, not both. Figma has the list specified
- [ ] Stakeholder connection > typo: add ANOTHER instead of an other
- [ ] Stakeholder connection> Individual> add the submitter as owner

**Comment by GeertSoet** [comment]
- [ ] Flex form: Financing resources detailed info section: should not have the field Year Founded
- [ ] Content type> Sub content> after selecting a sub content type, one can not unselect --> Can we do this by clicking again on the subcontent instead of the clear selection?

**Comment by GeertSoet** [comment]
Connect stakeholders >  Both individual and entity (owners) are mandatory > prefill with entity and individual that is filling. Uses can change from there
