### ISSUE TITLE
Flexible forms backend

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#590]
**To do**

- [ ] Submitter tab

- [ ] Update resource types (capacity building) 

- [ ] Add sub content type in database with ID 

- [ ] Basic info: Banner Photo (landscape format – Loic to provide correct sizing)

- [ ] Stakeholders Connections > Entity (Owner/Implementer, sponsor)

- [ ] Related Resources

- [ ] Basic WYSIWYG> How are we gonna send these values to backend? 

- [ ] Taxonomy, add: 
Trade and Investment
Chemicals and waste
Biological diversity
Marine and Freshwater
Climate and Atmosphere
Land and Agriculture
Environmental Governance

- [ ] event types: Options Dropdown: (Online, In Person, Hybrid)
- [ ] Event> url link

**Comment by diptigautam** [comment]
Hi! Could you add some more context to the tasks in this issue? I'll continue with these on Monday.

**Comment by GeertSoet** [comment]
I think this is obsolete nowadays in favor of: https://github.com/akvo/unep-gpml/issues/607
