### ISSUE TITLE
Discourse loading time

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#591]
**To reproduce** 
Navigate digital.gpmarinelitter.org/ > Connect stakeholders> communities. 

I noticed that it goes faster if you're already logged in at the digital.gpmarinelitter.org/ platform.

**Comment by GeertSoet** [comment]
Geert: When I access the url while being logged out and press login, this url takes 13s to reply

https://communities.gpmarinelitter.org/session/sso?return_path=%2F

Geert: Before is starts looking at https://unep-gpml.eu.auth0.com/authorize?client_id=BvsE68mvruXqW2mMBlnB55mxu5P9Zt2y&response_type=code&sso=bm9uY2U9ZTA1Mzg1YTA5MWNkOTE5OTY2MjVjMDdmOWI4MTVjMTImcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZjb21tdW5pdGllcy5ncG1hcmluZWxpdHRlci5vcmclMkZzZXNzaW9uJTJGc3NvX2xvZ2lu&sig=91c39acba5561007a571aa36ef0f4dc8299067e9e09ffc36ca4312238d1a1ce2

**Comment by lucassousaf** [comment]
@GeertSoet I can't reproduce this issue. For me, the loading times are OK, and it doesn't take too much to get a reply in all the scenarios I wrote above. Can you review this again, please?
