### ISSUE TITLE
Static links dont work with current authentication

### ISSUE THREAD

**Issue by tangrammer** [akvo/unep-gpml#597]
**Describe the bug**
UI keeps loading after an automatic attempt to re-login

**To Reproduce**
1. Go to [test](https://unep-gpml.akvotest.org/)
2. Try to log-in with admin user
3. Once your account is active, replace url and existent admin-url eg: https://unep-gpml.akvotest.org/edit-entity/10481 and reload page

 => Authentication doesn't work

**Comment by GeertSoet** [comment]
@GeertSoet Geert to test.

**Comment by GeertSoet** [comment]
@diptigautam also added you here, although I think it's a frontend problem. But let's try to get this one out of the way as well

**Comment by navins94** [comment]
It seems that Google is not properly configured thats why when we refresh the page is getting logged out. Need to rectify google settings
