### ISSUE TITLE
Auth0 popup improvements

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#600]
Full doc here: https://docs.google.com/document/d/1UjWW1ZQA4Rav-St_PsWNw6NaUOHTuHHd/edit?usp=sharing&ouid=116672611999466756570&rtpof=true&sd=true

- [x] When applying on behalf of an entity one should be provided with both options to sign up and log in – Issue 24 on the google sheet. It is important to have both options, since in some cases individuals that have already signed up may decide to apply on behalf of their entity later on. ( Issue 24 on the google sheet)

- [x] In Discourse (On the community page) > Pop-up Discourse should be replaced with Log In

- [ ] In Discourse > The Sign up functionality should be withdrawn from the community page as we want all users to go through the digital platform. Ideally add a link for those who have not signed up yet, to let them know that to log in they need to create an account first.

- [ ] When one accesses a link to the community page a disclaimer should be displayed informing them to log in to access the content. If possible, search should be removed. 

- [X] DONE: The top section should indicate the action e.g., Log in or Sign Up instead of GPML Digital Platform. In the pop up “apply for an entity” where both login and sign up apply the title should be removed
=>  https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login/prompt-login

### **WIP** Create an independent K8s oauth app id for unep
_Waiting for google verification_
- [x] The terms of services always be hyperlinked to this URL: https://digital.gpmarinelitter.org/privacy-policy-and-terms-of-use.pdf 

- [ ] When you choose to sign in/up with google it shows (Choose an account to continue to Akvo)" (Issue 23 on google sheet)

**Comment by GeertSoet** [comment]
@magnet I added you to this ticket, can talk you through if more context is needed.

**Comment by diptigautam** [comment]
Yeah, a bit more context around these would be nice. And could you also grant me access to the sheet?

**Comment by GeertSoet** [comment]
@all this ticket is on Review but it seem a few things are not implemented? 

Testing and still to be completed: 

In Discourse > The Sign up functionality should be withdrawn from the community page as we want all users to go through the digital platform. Ideally add a link for those who have not signed up yet, to let them know that to log in they need to create an account first.

When you choose to sign in/up with google it shows (Choose an account to continue to Akvo)" (Issue 23 on google sheet)

**Comment by GeertSoet** [comment]
Fixed the hyperlink to terms.
