### ISSUE TITLE
BE changes to support flexible forms 

### ISSUE THREAD

**Issue by tangrammer** [akvo/unep-gpml#607]
- [x] #640
- [x] #638

- [x] #639

- [x] #637

- [x] #644
- [x] #646

**Comment by tangrammer** [comment]
- Need to add two fields in backend for managing resource(Yes/No) and then one for the resource who is going to manage

Ownership rights already stored in recently created table `topic_stakeholder_auth` 

only rest add handler logic to parse FE payload `owners: [stakeholder-id]` and move adapted values to `topic_stakeholder_auth` db table

**Comment by GeertSoet** [comment]
@tangrammer  @navins94 did we also include capacity building here?

**Comment by navins94** [comment]
No we need to add capacity building

**Comment by GeertSoet** [comment]
To do 

- [ ] Add capacity building backend
