### ISSUE TITLE
Capacity building 

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#610]
**Design**
https://www.figma.com/file/FXcp4hL2BbI4F9lqG2XMF5/Phase-3-(Testing)?node-id=0%3A1

To do
- [x] Create static content

- [x] Add images and links to specific content

**Comment by ifirmawan** [comment]
let me try to take a look up for a moment

**Comment by loicsans** [comment]
Here is the list of capacity building resources: 
[Selection of capacity building resources-1.xlsx](https://github.com/akvo/unep-gpml/files/7702768/Selection.of.capacity.building.resources-1.xlsx)

**Comment by GeertSoet** [comment]
@UNEP we need the featured slideshow per content type.

**Comment by GeertSoet** [comment]
- [ ] UNEP we need the featured slideshow per content

**Comment by loicsans** [comment]
Here are the banner images for the capacity building page
[Archive.zip](https://github.com/akvo/unep-gpml/files/7726339/Archive.zip)

**Comment by ifirmawan** [comment]
> Here are the banner images for the capacity building page
> [Archive.zip](https://github.com/akvo/unep-gpml/files/7726339/Archive.zip)

Okay @loicsans , I'll implement it. Thanks

**Comment by loicsans** [comment]
@ifirmawan Check the design for the actual crop, if you want I can also crop them to the right piece of graphic

**Comment by ifirmawan** [comment]
Hi @loicsans Thanks, how about cropping image with exporting the image in Figma?
is the same way? FYI this is one of image that I already use it.
![course-n-training](https://user-images.githubusercontent.com/20871229/146365681-d7462342-17a0-4744-b009-f1b95a2202e0.png)

**Comment by GeertSoet** [comment]
@ifirmawan  
- [ ] Make whole box clickable

- [ ] The ratio of the left sidebar seems off, in the design it's less wide

- [ ] Let's discuss with Akvo team which sidebar items we'll have for now and where they should link to 

@unep 

- [ ] Where should the top banner link to?

**Comment by GeertSoet** [comment]
- [ ] Size: Icons and generally reduce dimensions --> align with https://datahub.gpmarinelitter.org/ [verify with Loic]
- [ ] Sidebar> remove "exchange"
- [ ] CounterMEASURE: Generating and disseminating knowledge about plastic pollution in Asian rivers and ...  > decrease fontsize to fit text
- [ ] Banner: Wrong dates on banner content: 18 January 2022 - Update dates, currently shows todays date
- [ ] Banner: In the banner update "webinar" label with corresponding category. (they are not all webinars)
- [ ] Card: Full title should always display. Reduce title size to show full text: "Circular Economy oriented Value Chain Guideline for Plastic Packaging Waste Utilisation"
- [ ] Image: Wrong image for Massive Open Online Course (MOOC) on Marine Litter [Geert add image]
- [ ] Remove white border around cards
- [ ] Text: don't capitalize "REDUCING PLASTIC POLLUTION":
- [ ] Text: Case Studies - Green title should be white (see Figma)
- [ ] See all buttons not working > link to resource library for now
- [ ] Height: they should be all the same height. We agreed on a characters limit for this purpose.> caused by image > tweak with Loic 
- [ ] Dropdown: the full title of the case study should show in the dropdown to give clarity on the subject of it.
- [ ] "Learn more" buttons should redirect to internal platform links not to external site (ADD LINK TO THE CORRECT SOURCE)
- [ ] Tags: they should not change colours when you hover over.
- [ ] Titles are incorrect please review the full list (ADD LINK TO THE CORRECT SOURCE) > Figma files are also correct
- [ ] Connections logos are incorrect > make dynamic based on related stakeholders of resource api

**Comment by ifirmawan** [comment]
I've connected with Loic and I'm ready fix all the feedbacks tomorrow

**Comment by GeertSoet** [comment]
Thanks for the update Iwan.

**Comment by ifirmawan** [comment]
I'm working on fixing the following issues :

- [ ] Set fixed width 117px for left sidebar
- [ ] Change background color #EDF2F7.
