### ISSUE TITLE
Best practises case studies

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#612]
https://www.figma.com/file/FXcp4hL2BbI4F9lqG2XMF5/Phase-3-(Testing)?node-id=0%3A1

**Comment by loicsans** [comment]
https://docs.google.com/spreadsheets/d/15wdViKcSuZNZYyh2rMVBFQOYQ3LkFdgeGEYuC5NHrmg/edit#gid=0
Here's the link to the 20 selected case studies

**Comment by GeertSoet** [comment]
- [ ] @UNEP share latest copy in gdcod

**Comment by GeertSoet** [comment]
- [ ]  Height: they should be all the same height. We agreed on a characters limit for this purpose.> caused by image > tweak with Loic
- [ ] Dropdown: the full title of the case study should show in the dropdown to give clarity on the subject of it.
- [ ] "Learn more" buttons should redirect to internal platform links not to external site (ADD LINK TO THE CORRECT SOURCE)
- [ ] Tags: they should not change colours when you hover over.
- [ ] Titles are incorrect please review the full list (ADD LINK TO THE CORRECT SOURCE) > Figma files are also correct
- [ ] Connections logos are incorrect > make dynamic based on related stakeholders of resource api

**Comment by GeertSoet** [comment]
- [ ] @loicsans add photos for all case studies
- [ ] @ifirmawan the transition is a bit funny, when it slides, you quickly see another pic. This shouldn't happen. 
- [ ] @ifirmawan @loicsans pair program on: The Text for the case studies and tags should fit within the display area 
- [ ] "Learn More" button it is not showing in all images.
- [ ] "Learn More" link does not redirect to the correct resources. 
- [ ] Case study icon utilised in the sidebar is incorrect. Please update.

**Comment by ifirmawan** [comment]
![image](https://user-images.githubusercontent.com/20871229/151744509-134e0476-0749-4383-acb0-c401d73c288e.png)

**Comment by GeertSoet** [comment]
- [ ] When transnational is containing a lot of countries the text gets skewed
<img width="1377" alt="Screenshot 2022-01-31 at 09 38 18" src="https://user-images.githubusercontent.com/13728925/151762494-1717f567-de35-488b-bd3a-5cdb52fb9959.png">

- [ ] Read more buttons are not showing
<img width="483" alt="Screenshot 2022-01-31 at 09 39 22" src="https://user-images.githubusercontent.com/13728925/151762640-d33b1715-f18e-466d-b6d2-b75fb6fb9300.png">

**Comment by GeertSoet** [comment]
- [ ] @GeertSoet update links based on Carolines email
