### ISSUE TITLE
Non member sign up issue

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#613]
https://drive.google.com/file/d/1mZEx-aF_MrjrEWtIZzNBhjPiJ2FEVYhb/view?usp=sharing

**Comment by GeertSoet** [comment]
POST
https://unep-gpml.akvotest.org/api/profile
Status
500
Internal Server Error
VersionHTTP/2
Transferred271 B (64 B size)
Referrer Policystrict-origin-when-cross-origin

alt-svc
    clear
content-length
    64
content-type
    application/json;charset=utf-8
date
    Mon, 06 Dec 2021 10:21:32 GMT
server
    nginx
via
    1.1 google
X-Firefox-Spdy
    h2

Accept
    application/json, text/plain, */*
Accept-Encoding
    gzip, deflate, br
Accept-Language
    en-US,en;q=0.5
Authorization
    Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhnZ0lPLTJ2LWZqbWljV1VXMjRiNSJ9.eyJuaWNrbmFtZSI6ImdlZXJ0KzI2IiwibmFtZSI6ImdlZXJ0KzI2QGFrdm8ub3JnIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyL2ZlYTY2N2M0YTU4ZDNkNDRhNDBkMjE1ODZkZDFlNzU0P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGZ2UucG5nIiwidXBkYXRlZF9hdCI6IjIwMjEtMTItMDZUMTA6MjA6NTUuMzk4WiIsImVtYWlsIjoiZ2VlcnQrMjZAYWt2by5vcmciLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vdW5lcC1ncG1sLXRlc3QuZXUuYXV0aDAuY29tLyIs…yNU5IRmtPVTNqd0p6WGhjcTVKIiwiaWF0IjoxNjM4Nzg2MDU2LCJleHAiOjE2Mzg4MjIwNTYsIm5vbmNlIjoiYTBVd2VGcFRTVEZpYWxjeVREbDBNRUpSYVVKMUxuWTBVSGxpVTFOU09YSlhOamRvTjA5NmVEVkpaUT09In0.lePlU_I0NXyF68Ig21qQahwXtuL1iT9mYzTqv3iVZQ9zf6dJh1x4GgcUfcmOfuuObdp1mZEIaGma3uSL0stXe0zA4uEiieUIgHB2pXonzw3yKSzIUL-nk4O1S6H3YyYsOJFGDR3Ufr3ztHwiJNvfrRj8e63PdwNLDGC3vwqp4EtG-i8lYKGLRuc_1bBn5_V-mlh_4tQaU1mPyMlXbTFgRMQu9Pc8F9FESqu9f4HelGqNaBXqKf0ICtK0xAORSHQFKQ3QT1Tc-XB-oNWQ4c_-Q1OrlimB54q7zOy1ibgKRH7LWfKnnhmiWrE6sk4OhKxQksqhsOV-smVqMJ5CzKTJiw
Connection
    keep-alive
Content-Length
    234
Content-Type
    application/json
Cookie
    stg_returning_visitor=Mon%2C%2006%20Dec%202021%2010:21:27%20GMT; stg_traffic_source_priority=1; stg_externalReferrer=; stg_last_interaction=Mon%2C%2006%20Dec%202021%2010:21:27%20GMT; _pk_id.1331070d-ea07-4a42-8b50-07e5e6e303b5.4548=9d5cb12781012920.1638786028.1.1638786028.1638786028.; _pk_ses.1331070d-ea07-4a42-8b50-07e5e6e303b5.4548=*; _legacy_auth0.is.authenticated=true; auth0.is.authenticated=true; profile=undefined
DNT
    1
Host
    unep-gpml.akvotest.org
Origin
    https://unep-gpml.akvotest.org
Referer
    https://unep-gpml.akvotest.org/stakeholder-signup
Sec-Fetch-Dest
    empty
Sec-Fetch-Mode
    cors
Sec-Fetch-Site
    same-origin
TE
    trailers
User-Agent
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0

**Comment by tangrammer** [comment]
"ERROR: insert or update on table \"stakeholder\" violates foreign key constraint \"stakeholder_non_member_organisation_fkey\"\n Detail: Key (non_member_organisation)=(10184) is not present in table \"non_member_organisation\"."

**Comment by tangrammer** [comment]
tested in `test` and promoting to prod the fix

**Comment by GeertSoet** [comment]
- I signed up affiliating with a non member organisation. In my profile/admin panel it says I'm a private citizen
- User: geert+27@akvo.org

Can we verify that the information is stored correctly in the db?
