### ISSUE TITLE
Add the posibility of rejecting a submission

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#62]
The submitted resource should have a *status* `SUBMITTED|APPROVED|REJECTED` right now there is no possibility of rejecting an event or profile. 

* By default any new submission starts with `SUBMITTED` status
* We need to add an `status` field to every resource table
* Consider changing the field `approved_at` to `reviewed_at`
* Consider adding `reviewed_by` referencing a `stakeholder` table
* Imported data gets inserted with `APPROVED`

**Comment by dedenbangkit** [comment]
@iperdomo what do you mean by every resource table? includes stakeholder table also? or just resource, policy, project and events?

**Comment by iperdomo** [comment]
> what do you mean by every resource table? includes stakeholder table also?

Yes, this also includes the `stakeholder` table

If you check the initial description: 
> right now there is no possibility of rejecting an event or **profile**

The profile is stored in the `stakeholder` table

**Comment by dedenbangkit** [comment]
```clojure
; --------------------------------------------------------------------------------
; (out) :duct.migrator.ragtime/applying 025-add-status-to-all-resource-table#5838568e
; (err) Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2553).
; (err) ERROR: column "status" of relation "policy" already exists
```

the wild idea will be to change the column name of policy status to policy_status

**Comment by iperdomo** [comment]
It would be good that we have a consistent name across tables. What about `approval_status` ?

**Comment by dedenbangkit** [comment]
ok, I'll refactor the code I made. So basically I was doing this:

```sql
CREATE TYPE status AS
ENUM ('SUBMITTED', 'APPROVED', 'REJECTED');

ALTER TABLE policy ADD COLUMN reviewed_at timestamptz;
ALTER TABLE policy ADD COLUMN reviewed_by integer REFERENCES stakeholder(id);
ALTER TABLE policy RENAME COLUMN status TO policy_status;
ALTER TABLE policy ADD COLUMN status status DEFAULT 'SUBMITTED';

-- ETC
```

and refactor the policy seed

**Comment by iperdomo** [comment]
@punchagan suggests `review_status` that is also an option

**Comment by dedenbangkit** [comment]
I think `review_status` is better.

**Comment by iperdomo** [comment]
The list of *pending* events is still showing *rejected* events
![2021-02-15_1638x647.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/ee083b9b-cb78-4ae9-a2be-66b7258589f2)

**Comment by dedenbangkit** [comment]
Does UI doesn't need a rejected list to re-open it? currently, the query is `<> 'APPROVED'` instead of `='SUBMITTED'`

**Comment by iperdomo** [comment]
It's confusing to have the list of *pending* with items that are already rejected. We don't show the status in the list.
Let's see what @loicsans thinks

**Comment by dedenbangkit** [comment]
Hi @loicsans, what do you think? should we keep reject to the list and have some rejected mark in the UI or just simply remove it from the list?

**Comment by loicsans** [comment]
@dedenbangkit, we shouldn't keep the rejected submission. Also thinking about rejecting (the action), we must have a modal to confirm the rejection: "Are you sure you want to reject this?"

**Comment by dedenbangkit** [comment]
![Screen Shot 2021-02-16 at 01.27.01.png](https://images.zenhubusercontent.com/600c532b852e9f29c0227e40/0dd0c901-3bf6-4cd7-8c4d-9c22157ddc69) @loicsans @iperdomo

**Comment by loicsans** [comment]
@dedenbangkit Let's make it "Are you sure you want to decline?" to match the action name

**Comment by dedenbangkit** [comment]
Ok @loicsans
