### ISSUE TITLE
Verify that all filters are available

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#648]
- [ ] In the new design there are several interactive filters that need to be available. 
- [ ] We have to take into account that the counting updates when I select a filter. For example if I select a geocoverage type, the count on the top should be calculated. 

<img width="571" alt="Screenshot 2021-12-23 at 11 26 34" src="https://user-images.githubusercontent.com/13728925/147227218-4a4268be-c303-4a08-b4c4-05b4f1179341.png">

**Comment by lucassousaf** [comment]
Hey @GeertSoet. Is this going to use the `/browse` API?
