### ISSUE TITLE
Stakeholder detail page - FE

### ISSUE THREAD

**Issue by navins94** [akvo/unep-gpml#690]

**Comment by navins94** [comment]
- [ ] Static frontend
- [ ] Connection with backend

**Comment by GeertSoet** [comment]
- [ ] Entity> remove authentication: one does not have to be authenticated to see entity page
- [ ] Remove expertise tags from banner and  showcase it under the offering section
- [ ] Own Resources should be Owned Resources
- [ ] Seeking  and offering tags should have total counts . See Figma file
- [ ] Tags: They are missing the label boundaries that have been used in the flexible forms. It would be great if we could add colours to tags.
- [ ] We currently do not have the entity detail view

**Comment by GeertSoet** [comment]
- [ ] Entity> show actual value instead of helcom
- [ ] Update owned/favorite to be dynamic
- [ ] Double check that entity profile is shown when coming from stakeholder overview.

**Comment by GeertSoet** [comment]
- [ ] Entity Icon is incorrect, currently shows Hellcom icon for all.
