### ISSUE TITLE
Change logo to temporary one + header links

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#70]
* **Logo** - There is an on-going process of approving a new logo. We need to use the new temporary logo. UNEP will provide it by Tuesday 9th.
* **UN Environment Programme** -> https://www.unep.org
* **GPML** -> https://www.gpmarinelitter.org/

**Comment by dedenbangkit** [comment]
waiting for UNEP logo

**Comment by dedenbangkit** [comment]
is there any update on temporary logo?

**Comment by iperdomo** [comment]
@dedenbangkit nothing, let's keep the one we have. I'll reopen the issue after the demo
