### ISSUE TITLE
Footer & Integrations

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#73]
> We will use this Footer across the on the GPML website and GPML
Digital Platform Data Hub component. No need to have a vertical
menu bar for now

![2021-02-05_1061x666.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/4731b779-42bb-48ea-ab1c-0d083e8cbc35)

**Comment by iperdomo** [comment]
![2021-02-11_1258x695.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/aaab9066-4960-4da0-991e-9f9afc7bbb87)

**Comment by iperdomo** [comment]
> The Digital Platform is a UNEP contribution to the Global Partnership on Marine Litter

**Comment by loicsans** [comment]
![Screenshot 2021-02-11 at 12 23 03](https://user-images.githubusercontent.com/1717219/107624680-e9806500-6c63-11eb-83a7-903f1a84227f.png)
It looks like that now
