### ISSUE TITLE
Complete your signup message

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#75]
Note: Subject to change, based on the data on Tuesday 9th

* Click on the link we sent in your email to verify your email address
* We will review your sign-up request as soon as you verify your email address. Please, allow for 1 business day

**Comment by iperdomo** [comment]
The *warning* about the link must only be shown if the email is not verified.
See the last line of the diff. It was checking `user?.email_verified === false`
```udiff

diff --git a/frontend/src/modules/events/event-warning-modal.jsx b/frontend/src/modules/events/event-warning-modal.jsx
deleted file mode 100644
index 0812031..0000000
--- a/frontend/src/modules/events/event-warning-modal.jsx
+++ /dev/null
@@ -1,30 +0,0 @@
-import { Modal, Button } from "antd";
-import { useAuth0 } from '@auth0/auth0-react';
-
-const EventWarningModal = ({visible, close}) => {
-    const {user} = useAuth0();
-    return (
-        <Modal
-          width={600}
-          okText="Close"
-          visible={visible}
-          className="event-warning-modal"
-          footer={<Button onClick={e => close()}>Close</Button>}
-          closable={false}
-        >
-          <div className="submitted">
-            <h2>Pending approval</h2>
-            <p>
-              We will review your account shortly.
-              You can add an <strong>event</strong> once your account is approved.
-              {user?.email_verified === false && <span><br />

```

**Comment by dedenbangkit** [comment]
Hi @iperdomo there is no file call `event-warning-modal.jsx` anymore. I moved it here: `https://github.com/akvo/unep-gpml/blob/main/frontend/src/utils/modal-warning-user.jsx`

**Comment by iperdomo** [comment]
I know that there is no file anymore, I'm showing the boolean check we had and now we don't. Before we checked that if the user's email was already verified. If that is the case we **don't** show the message about clicking the link in the email, because we don't send an email

**Comment by dedenbangkit** [comment]
Yes, something like this? [modal-warning-user.jsx#L16](https://github.com/akvo/unep-gpml/blob/main/frontend/src/utils/modal-warning-user.jsx#L16)

**Comment by iperdomo** [comment]
I sign-up with Google account and I keep getting the email validation link message. My email is already validated.
![2021-02-17_634x290.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/fc783e07-e195-4cc9-a1e4-021d08f5a145)

**Comment by iperdomo** [comment]
We still have a misleading message. We're not sending *any* email to accounts login with Google or LinkedIn.
![2021-02-18_991x366.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/ba976986-342e-4619-ad30-d87cf93a9cf8)
