### ISSUE TITLE
Updating profile after sign-up

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#80]
When logging with a Google Account the JWT claims contains the `picture` of the user.
If you attempt to update your profile just after creating it, it fails with HTTP 500

**Comment by iperdomo** [comment]
The flag `I'm a private citizen` is not getting stored

**Comment by dedenbangkit** [comment]
I'm a private citizen equal to affiliation is NULL isn't it?

**Comment by iperdomo** [comment]
The problem is that when I visit my profile, the *I'm a private citizen* is **not** checked, so when I tried to save my changes, I can't because of the *required* fields on Organization.

**Comment by dedenbangkit** [comment]
fixed by @martinchristov commit: https://github.com/akvo/unep-gpml/commit/1b7aa71d12bb581a19663490416190c3fe626770
