### ISSUE TITLE
Scroll to top when using footer links

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#84]
In order to avoid a full page refresh via `<a href="/browse?[...]></a>` we're using a `<Link>` component in the footer. When using this links the application keeps the scroll position at the bottom of the page, while the *natural* behavior is to scroll to top.

Relevant info: https://stackoverflow.com/a/54343182

**Comment by martinchristov** [comment]
I pushed a commit that fixes the issue of scrolling.
I tried first to implement <ScrollToTop />, but then there was also another bigger issue. To make this work with <Links> in footer I would have had to change the way the filters work currently. The time needed for this implementation is not worth investing for a very slight UX improvement in the rare case of navigating to /browse from footer.
