### ISSUE TITLE
Add icons to distinguish the different type of resources

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#88]
Add *icons* to identify each type of resource, those can be used in
1. Landing page (latest resource)
2. Browse view

**Comment by martinchristov** [comment]
I can pick this up after @loicsans provides icons. You can just paste here the link to a developer version of XD shared design. (hopefully I would be able to copy as svg)

**Comment by loicsans** [comment]
How urgent is this @iperdomo ?
