### ISSUE TITLE
Add email address to topbar

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/unep-gpml#90]
Based on the issue from @iperdomo 11 02 2021:

Iván: Update
- I promoted the changes to production
- I asked Marta to join the platform to make her admin
- I approved her
- Now she reports that she had to enter the details again :surprise:

found the issue: she joined with 2 different email addresses @un.org and @unep.org

What I suggested was to add the email address to the topbar

**Comment by martaotto** [comment]
Love the story! I think we can close this. 

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/abea2909-efb5-4541-84ac-0a2792a096b7)
