### ISSUE TITLE
Organization list cleanup

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#95]
We have several *UNEP* organizations
![2021-02-15-072324_1920x1080_scrot.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/4a78d203-c9f1-4ed6-9d44-21997ed76591)

**Comment by dedenbangkit** [comment]
Are these consider as data cleaning? if yes, I'll add it as part of [data-transform.ipynb](https://github.com/akvo/unep-gpml/blob/main/doc/data-transform.ipynb)

**Comment by iperdomo** [comment]
We don't need to do data-cleaning but we should report this problem to UNEP. From where this different values are coming from?

**Comment by dedenbangkit** [comment]
@iperdomo 

- United Nations Environment Programme: Project, Resource.
- United Nation Environment Programme, United Nations Environmental Programme: Resource.

**Comment by martaotto** [comment]
Caroline is working on cleaning the flat file to resolve all issues

**Comment by GeertSoet** [comment]
@martaotto do you happen to have an update on this?

**Comment by GeertSoet** [comment]
- Caroline: reason we have duplicates: list of entities comes from different sources e.g. Technical resources, list of entities. Sarah provides correct list. 

Source of truth is entities profile list. This entity profile should be editable.

**Comment by chebbett** [comment]
The entities have been cleaned for all the resources in the flat file and for the entities (official GPML members) file to ensure uniformity. This will avoid having duplicates in the drop-down list of entities.

**Comment by GeertSoet** [comment]
On test.
