### ISSUE TITLE
Details view of Projects

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#96]
* Project item in the browse view has a *Learn more* button
* Details about *Project* is shown
* Page 32 of feedback pdf

**Comment by iperdomo** [comment]
@martinchristov I've changed the button from `Visit Dashboard` to `Visit Website` sin the the `url` value in the response is the actual website of the project. 
We need to add a new `Visit Dashboard` that links directly to `https://unep.tc.akvo.org` always.

**Comment by martinchristov** [comment]
@iperdomo I've added a button `Visit Dashboard` only for projects. It might be that more than one button would appear in some cases.

**Comment by iperdomo** [comment]
All projects have a fixed link that points to https://unep.tc.akvo.org

See this example: https://unep-gpml.akvotest.org/project/949

We should have 2 links:
* Visit website: https://g20mpl.org/partners/japan
* Visit Dashboard: https://unep.tc.akvo.org
