### ISSUE TITLE
Change *Add Event* to *Add*

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#98]
* Back to original mock-up of `Add` @loicsans needs to design how to deal with the other *resources*, show-up but disabled?
* Page 37 of feedback file

**Comment by loicsans** [comment]
https://xd.adobe.com/view/608f6666-aa71-4a4d-990e-3399ee1cabca-35dc/
Let's just have a dropdown with "events" in it, nothign else until we can serve the other forms
